"""Render the user's STEP room with the new rail-mount CAD meshes.

blender -b --factory-startup --python rail-mount/render_room.py -- --preview
Optional: --view room|mount|overview. No geometry is generated by AI images.
"""
import bpy, math, json, sys, random
from pathlib import Path
from mathutils import Vector, Matrix
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'render'
PREVIEW='--preview' in sys.argv
VIEW=sys.argv[sys.argv.index('--view')+1] if '--view' in sys.argv else 'all'
random.seed(24)
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
scene=bpy.context.scene
scene.unit_settings.system='METRIC'

def material(name,color,rough=.5,metal=0,noise=0):
    m=bpy.data.materials.new(name);m.use_nodes=True
    p=m.node_tree.nodes.get('Principled BSDF');p.inputs['Base Color'].default_value=(*color,1)
    p.inputs['Roughness'].default_value=rough;p.inputs['Metallic'].default_value=metal
    if noise:
        n=m.node_tree.nodes.new('ShaderNodeTexNoise');n.inputs['Scale'].default_value=noise;n.inputs['Detail'].default_value=2
        b=m.node_tree.nodes.new('ShaderNodeBump');b.inputs['Strength'].default_value=.15;b.inputs['Distance'].default_value=.0006
        m.node_tree.links.new(n.outputs['Fac'],b.inputs['Height']);m.node_tree.links.new(b.outputs['Normal'],p.inputs['Normal'])
    return m

plaster=material('Warm chalk / mineral plaster',(.72,.69,.62),.88,noise=130)
ivory=material('Soft ivory cabinet lacquer',(.78,.77,.72),.38)
oak=material('Oiled honey oak',(.36,.20,.085),.48)
walnut=material('Rail / warm beech',(.32,.15,.064),.5)
for m,c1,c2 in [(oak,(.22,.105,.035,1),(.48,.29,.13,1)),(walnut,(.16,.065,.025,1),(.40,.23,.11,1))]:
    n=m.node_tree.nodes;l=m.node_tree.links;p=n.get('Principled BSDF')
    tex=n.new('ShaderNodeTexCoord');mult=n.new('ShaderNodeVectorMath');mult.operation='MULTIPLY';mult.inputs[1].default_value=(45,2,7)
    noise=n.new('ShaderNodeTexNoise');noise.inputs['Scale'].default_value=3;noise.inputs['Detail'].default_value=3
    ramp=n.new('ShaderNodeValToRGB');ramp.color_ramp.elements[0].color=c1;ramp.color_ramp.elements[1].color=c2
    l.new(tex.outputs['Generated'],mult.inputs[0]);l.new(mult.outputs[0],noise.inputs['Vector']);l.new(noise.outputs['Fac'],ramp.inputs[0]);l.new(ramp.outputs[0],p.inputs['Base Color'])
linen=material('Sage linen duvet',(.20,.28,.235),.95,noise=260)
linenlight=material('Flax washed linen',(.65,.60,.48),.96,noise=280)
cream=material('Warm white cotton',(.80,.78,.70),.94,noise=250)
rust=material('Burnt sienna cushion',(.36,.13,.065),.9,noise=240)
black=material('Soft charcoal',(.014,.019,.020),.6)
polymer=material('Mount / midnight graphite PETG',(.035,.052,.060),.48,noise=450)
armmat=material('Mount / muted bronze polymer',(.23,.13,.072),.5,noise=450)
steel=material('Satin zinc steel',(.45,.48,.49),.28,.85)
rubber=material('Rubber driver suspension',(.008,.010,.012),.82)
cone=material('Woven composite cone',(.065,.073,.077),.72,noise=250)
webbing=material('Black retaining webbing',(.011,.015,.016),.94,noise=350)
orange=material('Prusa orange',(.66,.14,.018),.45)
leafmat=material('Olive green leaves',(.08,.16,.055),.65)
ceramic=material('Glazed cream ceramic',(.73,.66,.53),.28)
bookcolors=[material('Book spine '+str(i),c,.78) for i,c in enumerate([(.23,.28,.27),(.65,.47,.28),(.57,.21,.11),(.75,.71,.57),(.18,.22,.27)])]

def box(name,loc,size,mat,bevel=0):
    bpy.ops.mesh.primitive_cube_add(size=1,location=loc);o=bpy.context.object;o.name=name;o.dimensions=size
    bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
    if mat:o.data.materials.append(mat)
    if bevel:
        mod=o.modifiers.new('Soft edges','BEVEL');mod.width=bevel;mod.segments=3
        o.modifiers.new('Corner normals','WEIGHTED_NORMAL')
    return o

def cyl(name,loc,r,depth,mat,axis=(0,0,1),r2=None):
    if r2 is None:bpy.ops.mesh.primitive_cylinder_add(vertices=48,radius=r,depth=depth,location=loc)
    else:bpy.ops.mesh.primitive_cone_add(vertices=48,radius1=r,radius2=r2,depth=depth,location=loc)
    o=bpy.context.object;o.name=name;o.rotation_mode='QUATERNION';o.rotation_quaternion=Vector((0,0,1)).rotation_difference(Vector(axis));o.data.materials.append(mat)
    for p in o.data.polygons:p.use_smooth=True
    return o

def curve(name,points,r,mat):
    c=bpy.data.curves.new(name,'CURVE');c.dimensions='3D';c.bevel_depth=r;c.bevel_resolution=3
    s=c.splines.new('BEZIER');s.bezier_points.add(len(points)-1)
    for b,p in zip(s.bezier_points,points):b.co=p;b.handle_left_type='AUTO';b.handle_right_type='AUTO'
    o=bpy.data.objects.new(name,c);scene.collection.objects.link(o);o.data.materials.append(mat);return o

def uvball(name,loc,size,mat):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=32,ring_count=20,location=loc);o=bpy.context.object;o.name=name;o.scale=size;o.data.materials.append(mat)
    for p in o.data.polygons:p.use_smooth=True
    return o

def mesh(name,vertices,faces,mat,scale=.001):
    data=bpy.data.meshes.new(name);data.from_pydata(vertices,[],faces);data.update()
    o=bpy.data.objects.new(name,data);scene.collection.objects.link(o);o.scale=(scale,)*3
    o.data.materials.append(mat);return o

# Import source objects with the complete native placements, including the
# existing architectural shell and its real window opening and entrance.
architecture=[];furniture=[]
for r in json.loads((OUT/'room_meshes.json').read_text()):
    name=r['name']
    if name in ['Part__Feature307','Part__Feature308']:continue # Relocated to the rail below.
    mat=ivory
    if name.startswith('Architecture'):mat=plaster
    elif name in ['Part__Feature310','Part__Feature311']:mat=walnut
    elif name=='Part__Feature008':mat=linenlight
    elif name=='Part__Feature009':mat=black
    elif name=='Turntable_v2':mat=black
    elif name=='Prusa_i3_MK2_v2':mat=black
    o=mesh(r['label']+' / '+name,r['vertices'],r['faces'],mat)
    if name.startswith('Architecture'):
        architecture.append(o)
        # Original horizontal floor surfaces receive oak.
        zs=[v[2] for v in r['vertices']]
        if zs and max(zs)-min(zs)<.1 and abs(zs[0])<1:o.data.materials[0]=oak
    elif name=='Prusa_i3_MK2_v2':
        # The imported printer contains very fine threaded components.
        mod=o.modifiers.new('Render simplification','DECIMATE');mod.ratio=.10
    else:
        mod=o.modifiers.new('Subtle furniture edge highlights','BEVEL');mod.width=1.2;mod.segments=2
        o.modifiers.new('Furniture normals','WEIGHTED_NORMAL');furniture.append(o)
    if name=='Rodulf_Hæve_sænke_bord_v4':
        o.data.materials.append(black)
        for face in o.data.polygons:
            if face.center.z>790:face.material_index=1

# Main living zone floor follows the 2.55 x 4.40 m STEP outline. Board detailing.
for row in range(15):
    x=(row+.5)*.17
    for j in range(5):
        lo=max(0,j*1.10-(.55 if row%2 else 0));hi=min(4.4,j*1.10+1.097-(.55 if row%2 else 0))
        if hi>lo:box('Oak board',(x,(lo+hi)/2,.004),(.168,hi-lo,.008),oak,.0007)
ceiling=box('Ceiling — main room',(1.275,2.2,2.66),(2.75,4.6,.12),plaster)
for x in [.012,2.538]:box('Slim white skirting',(x,2.2,.038),(.018,4.4,.076),ivory,.002)

# Exact window opening from the model: x=.0894..2.4894, sill=.970, head=2.170.
glass=material('Cool window daylight',(.57,.69,.78),.18)
p=glass.node_tree.nodes.get('Principled BSDF');p.inputs['Emission Color'].default_value=(.64,.78,.94,1);p.inputs['Emission Strength'].default_value=.5
window=box('Window glazing',(1.2894,-.06,1.57),(2.4,.015,1.2),glass)
window.visible_shadow=False
for x in [.11,1.29,2.47]:box('Window upright',(x,-.025,1.57),(.038,.07,1.22),ivory,.003)
for z in [.98,2.16]:box('Window sill and header',(1.29,.012,z),(2.40,.10,.035),ivory,.002)
# Gathered curtains stay beside the window, leaving the source desk in place.
for side,x0 in [('left',.05),('right',2.30)]:
    vs=[];fs=[];nu,nv=30,40
    for j in range(nv+1):
        z=.11+j/nv*2.24
        for i in range(nu+1):
            x=x0+i/nu*.20;y=.09+.025*math.sin(i/nu*math.pi*10)+.01*math.sin(j*.25)
            vs.append((x,y,z))
    for j in range(nv):
        for i in range(nu):a=j*(nu+1)+i;fs.append((a,a+1,a+nu+2,a+nu+1))
    o=mesh('Gathered linen curtain '+side,vs,fs,cream,1)
    for p in o.data.polygons:p.use_smooth=True

# Bedding dresses the actual 1200 x 2000 bed footprint; no furniture is moved.
box('Mattress textile top',(.68276,3.35297,.453),(1.185,1.985,.035),cream,.035)
nu,nv=60,90;vs=[];fs=[]
for j in range(nv+1):
    y=2.36+1.98*j/nv
    for i in range(nu+1):
        x=.09+1.185*i/nu
        edge=min(i/nu,1-i/nu,j/nv,1-j/nv)
        z=.495+.009*math.sin(x*23+y*8)+.007*math.sin(y*26+x*9)+.004*math.sin(y*51)
        z-=.065*math.exp(-edge*70)
        vs.append((x,y,z))
for j in range(nv):
    for i in range(nu):a=j*(nu+1)+i;fs.append((a,a+1,a+nu+2,a+nu+1))
o=mesh('Soft sage duvet / draped surface',vs,fs,linen,1)
for p in o.data.polygons:p.use_smooth=True
sol=o.modifiers.new('Duvet loft','SOLIDIFY');sol.thickness=.022
for y in [3.10,3.60]:
    o=box('Backrest pillow at TV seating',(.28,y,.68),(.21,.53,.46),cream,.095);o.rotation_euler.y=-.16
o=box('Rust accent cushion',(.44,3.83,.62),(.20,.35,.34),rust,.075);o.rotation_euler=(.12,.2,.12)
# Folded throw at the foot of the bed, away from the middle listening position.
vs=[];fs=[]
for j in range(31):
    for i in range(61):
        x=.14+i/60*1.10;y=2.43+j/30*.40
        z=.528+.008*math.sin(x*34+y*14)+.004*math.sin(x*77)-.04*math.exp(-min(i,60-i)*.7)
        vs.append((x,y,z))
for j in range(30):
    for i in range(60):a=j*61+i;fs.append((a,a+1,a+62,a+61))
o=mesh('Folded linen throw',vs,fs,linenlight,1)
for p in o.data.polygons:p.use_smooth=True
o.modifiers.new('Folded textile thickness','SOLIDIFY').thickness=.014

# Media wall: original cabinet shapes, with small belongings and recognizable TV.
screen=material('TV / quiet fjord landscape',(.10,.19,.22),.25)
n=screen.node_tree.nodes;l=screen.node_tree.links;p=n.get('Principled BSDF')
tex=n.new('ShaderNodeTexCoord');sep=n.new('ShaderNodeSeparateXYZ');l.new(tex.outputs['Generated'],sep.inputs[0])
ramp=n.new('ShaderNodeValToRGB');ramp.color_ramp.elements[0].color=(.018,.045,.060,1);ramp.color_ramp.elements[1].color=(.38,.49,.50,1)
l.new(sep.outputs['Z'],ramp.inputs[0]);l.new(ramp.outputs[0],p.inputs['Base Color']);l.new(ramp.outputs[0],p.inputs['Emission Color']);p.inputs['Emission Strength'].default_value=.32
box('TV screen',(2.3115,2.55126,1.2358),(.003,1.084,.620),screen,.007)
for idx,(heights,color) in enumerate([([.22,.33,.27,.46,.30,.35,.20,.27],(.14,.23,.25)),([.12,.20,.17,.24,.19,.27,.13,.18],(.045,.115,.145))]):
    ma=material('TV ridge '+str(idx),color,.7)
    vs=[(2.309-idx*.001,2.011,.926),(2.309-idx*.001,3.091,.926)]+[(2.309-idx*.001,3.091-i*1.08/7,.926+h) for i,h in enumerate(reversed(heights))]
    mesh('TV landscape ridge',vs,[list(range(len(vs)))],ma,1)
cyl('TV pale sun',(2.306,2.30,1.435),.040,.001,ceramic,(-1,0,0))
for y in [1.50,3.42]:
    for i in range(7):
        h=random.uniform(.16,.24)
        box('Books on media cabinet',(2.36,y+i*.022,.70+h/2),(.15,.019,h),bookcolors[i%5],.001)
# Visible orange printer frame detail tracks the imported printer envelope.
box('Prusa frame accent',(2.48,1.05,1.05),(.025,.32,.018),orange,.002)
# Desk laptop and small accessories are explicitly styling additions.
box('Laptop base',(1.31,.40,.785),(.34,.24,.012),steel,.006)
o=box('Laptop display',(1.31,.285,.89),(.34,.012,.21),black,.008);o.rotation_euler.x=-.12
box('Desk notebook',(.95,.51,.785),(.16,.22,.014),bookcolors[3],.003)
cyl('Desk ceramic mug',(1.73,.48,.82),.037,.085,ceramic)
cyl('Coffee in mug',(1.73,.48,.864),.030,.001,black)

def plant(loc,scale=1):
    x,y,z=loc
    cyl('Plant pot',(x,y,z+.065*scale),.075*scale,.13*scale,ceramic,r2=.065*scale)
    for i in range(9):
        a=i*2.4;h=random.uniform(.20,.37)*scale
        tip=(x+math.cos(a)*.08*scale,y+math.sin(a)*.08*scale,z+h)
        curve('Plant stem',[(x,y,z+.10*scale),(x,y,z+h*.8),tip],.002*scale,leafmat)
        o=uvball('Plant leaf',tip,(.025*scale,.010*scale,.062*scale),leafmat);o.rotation_euler=(.5,a,.3)
plant((2.36,3.59,.702),.9)

# Wall-safe styling light sits on furniture; no extra fixing holes are implied.
cyl('Small lamp base',(2.34,4.15,1.068),.075,.018,black)
cyl('Small lamp stem',(2.34,4.15,1.20),.006,.26,steel)
cyl('Linen lamp shade',(2.34,4.15,1.34),.105,.19,linenlight,r2=.075)

def around(point,angle,axis):return Matrix.Translation(point)@Matrix.Rotation(math.radians(angle),4,axis)@Matrix.Translation(-Vector(point))

mount_data=json.loads((OUT/'mount_meshes.json').read_text())
installation=json.loads((OUT/'installation.json').read_text())
mount_objects=[]
def transformed(o,mat):
    bpy.context.view_layer.update();o.matrix_world=mat@o.matrix_world;return o

def speaker(name,mat,active=False):
    objects=[]
    def b(*args,**kw):o=box(*args,**kw);objects.append(o);return o
    def c(*args,**kw):o=cyl(*args,**kw);objects.append(o);return o
    b(name+' / Eris cabinet',(0,.320,0),(.141,.162,.210),black,.004)
    b(name+' / front baffle',(0,.4005,0),(.135,.002,.204),black,.003)
    for z,r in [(-.033,.0445),(.066,.019)]:
        c(name+' / driver flange',(0,.402,z),r,.0025,black,(0,1,0))
        bpy.ops.mesh.primitive_torus_add(major_segments=48,minor_segments=12,location=(0,.404,z),major_radius=r*.83,minor_radius=r*.105,rotation=(math.pi/2,0,0))
        o=bpy.context.object;o.name=name+' / rubber surround';o.data.materials.append(rubber);objects.append(o)
        c(name+' / woven cone',(0,.404,z),r*.73,.005,cone,(0,1,0),r2=r*.38)
        o=uvball(name+' / dome',(0,.407,z),(r*.31,.004,r*.31),black);objects.append(o)
    b(name+' / rear amplifier panel',(0,.238,-.016),(.10,.002,.13),black,.003)
    c(name+' / rear reflex port',(0,.236,.077),.019,.004,rubber,(0,1,0))
    if active:
        c(name+' / volume knob',(.048,.405,-.079),.009,.007,black,(0,1,0))
        led=material('Blue power LED',(.05,.22,.7),.2)
        p=led.node_tree.nodes.get('Principled BSDF');p.inputs['Emission Color'].default_value=(.08,.32,1,1);p.inputs['Emission Strength'].default_value=2
        c(name+' / power LED',(.047,.409,-.095),.0018,.001,led,(0,1,0))
    for x in [-.018,.018]:c(name+' / rear socket',(x,.235,-.04),.004,.008,steel,(0,1,0))
    # Foam supports, two continuous webbing loops and buckles on top.
    b(name+' / base pad',(0,.320,-.107),(.141,.162,.004),rubber,.001)
    for x in [-.0735,.0735]:
        for y in [.27225,.36775]:b(name+' / side pad',(x,y,-.05),(.006,.0595,.105),rubber,.001)
        b(name+' / side pad',(x,.320,-.06025),(.006,.036,.0845),rubber,.001)
    for y in [.262,.376]:
        outline=[(-.0855,-.1186),(.0855,-.1186),(.0855,.013),(.07125,.015),(.07125,.106),(-.07125,.106),(-.07125,.015),(-.0855,.013)]
        vs=[(x,y+dy,z) for x,z in outline for dy in [-.010,.010]]
        fs=[(2*i,2*((i+1)%8),2*((i+1)%8)+1,2*i+1) for i in range(8)]
        o=mesh(name+' / fitted webbing loop',vs,fs,webbing,1);o.modifiers.new('Webbing thickness','SOLIDIFY').thickness=.0012;objects.append(o)
        b(name+' / strap buckle',(.035,y,.111),(.030,.024,.006),black,.002)
    for o in objects:transformed(o,mat)
    return objects

for idx,place in enumerate(installation['placements']):
    along=place['rail_centre_along_room_mm']/1000
    base=Matrix.Translation((.040,along,2.075))@Matrix.Rotation(-math.pi/2,4,'Z')
    yaw=around((0,.135,0),place['pan_deg'],'Z')
    tilt=around((0,.320,0),place['installed_tilt_deg'],'X')
    def empty(name,parent=None,loc=(0,0,0)):
        o=bpy.data.objects.new(name,None);scene.collection.objects.link(o);o.empty_display_size=.035;o.parent=parent;o.location=loc;return o
    control=empty(place['name']+' / AIM CONTROLS');control.matrix_world=base
    control['pan_deg']=place['pan_deg'];control['tilt_step']=round(-place['installed_tilt_deg']/5)
    control.id_properties_ui('pan_deg').update(min=-90,max=90,description='Continuous pan, degrees. Validated design range ±90.')
    control.id_properties_ui('tilt_step').update(min=0,max=12,description='Each step is 5 degrees down; 0=level, 12=60 degrees down.')
    panrig=empty(place['name']+' / pan pivot',control,(0,.135,0))
    tiltrig=empty(place['name']+' / tilt pivot',panrig,(0,.185,0))
    for obj,axis,prop,expression in [(panrig,2,'pan_deg','angle*pi/180'),(tiltrig,0,'tilt_step','-angle*pi/36')]:
        fc=obj.driver_add('rotation_euler',axis);drv=fc.driver;drv.type='SCRIPTED'
        var=drv.variables.new();var.name='angle';var.targets[0].id=control;var.targets[0].data_path='["'+prop+'"]';drv.expression=expression
    bpy.context.view_layer.update()
    def parent_preserve(o,parent):
        world=o.matrix_world.copy();o.parent=parent;o.matrix_world=world
    for r in mount_data:
        # Concrete shanks extend into the wall and are naturally occluded.
        o=mesh(place['name']+' / '+r['name'],r['vertices'],r['faces'],steel if r.get('hardware') else armmat if r['name']=='Pan_Yoke' else polymer)
        transform=base@(yaw@tilt if r['kind']=='cradle' else yaw if r['kind']=='yoke' else Matrix.Identity(4))
        transformed(o,transform);parent_preserve(o,{'fixed':control,'yoke':panrig,'cradle':tiltrig}[r['kind']]);mount_objects.append(o)
    cabinets=speaker(place['name'],base@yaw@tilt,active=idx==0)
    for o in cabinets:parent_preserve(o,tiltrig)
    mount_objects.extend(cabinets)
    plug=base@yaw@tilt@Vector((-.018,.225,-.04))
    curve(place['name']+' / service loop',[plug,(.13,along,1.94),(.054,along,2.045),(.049,along-.25,2.044)],.0025,black)
# Shared low-profile cable run follows the timber; clips attach to timber only.
curve('Cable alongside rail',[(.048,2.15,2.044),(.048,3.2,2.044),(.048,4.31,2.044)],.0025,black)
for y in [2.3,2.8,3.3,3.8,4.25]:box('Rail cable clip',(.052,y,2.045),(.009,.010,.010),polymer,.002)

def area(name,loc,target,power,color,size):
    bpy.ops.object.light_add(type='AREA',location=loc);o=bpy.context.object;o.name=name;o.data.energy=power;o.data.color=color;o.data.shape='DISK';o.data.size=size
    o.rotation_euler=(Vector(target)-o.location).to_track_quat('-Z','Y').to_euler();return o
area('Window / soft afternoon sky',(1.28,.16,1.75),(1.25,3,.7),100,(.77,.86,1),1.65)
area('Ceiling bounce',(1.3,2.5,2.52),(1.3,2.5,0),60,(1,.86,.67),2.1)
area('Doorway / soft fill',(1.7,4.28,2.25),(.4,2.5,1.4),35,(1,.87,.73),1.2)
area('Table lamp glow',(2.34,4.15,1.25),(2.54,4.1,1.15),4,(1,.59,.25),.16)
bpy.ops.object.light_add(type='SUN',location=(1,-2,3));sun=bpy.context.object;sun.name='Late afternoon sun';sun.data.energy=2.0;sun.data.angle=.07;sun.data.color=(1,.79,.55)
sun.rotation_euler=(Vector((.8,3.7,.1))-Vector((1,-2,3))).to_track_quat('-Z','Y').to_euler()
scene.world=bpy.data.worlds.new('Blue afternoon environment');scene.world.use_nodes=True;scene.world.node_tree.nodes['Background'].inputs[0].default_value=(.46,.59,.75,1);scene.world.node_tree.nodes['Background'].inputs[1].default_value=.22
scene.render.engine='CYCLES';scene.cycles.device='CPU';scene.cycles.samples=24 if PREVIEW else 160
try:
    prefs=bpy.context.preferences.addons['cycles'].preferences;prefs.compute_device_type='OPTIX';prefs.get_devices()
    if any(d.type=='OPTIX' for d in prefs.devices):
        for d in prefs.devices:d.use=d.type=='OPTIX'
        scene.cycles.device='GPU'
except Exception as exc:print('CPU rendering fallback',exc)
scene.cycles.use_denoising=True;scene.cycles.max_bounces=8
scene.render.threads_mode='FIXED';scene.render.threads=12
scene.render.image_settings.file_format='PNG';scene.render.resolution_percentage=100
scene.view_settings.view_transform='AgX'
scene.view_settings.look='AgX - Medium High Contrast'
scene.view_settings.exposure=-.30

def camera(name,loc,target,lens):
    bpy.ops.object.camera_add(location=loc);o=bpy.context.object;o.name=name;o.data.lens=lens;o.data.clip_start=.01
    o.rotation_euler=(Vector(target)-o.location).to_track_quat('-Z','Y').to_euler();return o
wide=camera('01 / furnished room',(1.275,6.50,1.60),(1.275,2.20,1.28),28)
close=camera('02 / rail mount detail',(.95,3.52,2.25),(.20,2.93,2.045),54)
overview=camera('03 / architectural cutaway',(-4.3,7.1,5.5),(1.1,2.35,.85),48)
railview=camera('04 / both surrounds above the bed',(2.43,3.24,1.78),(.04,3.35,1.40),25)
scene.camera=wide
scene['Source']='Actual Værelse 65 POP STEP architecture and furniture, plus rail-mount CAD. Surface materials, bedding and small decor are visualization choices.'
scene['Mount']='Eris rail mount engineering prototype; no assigned safe working load.'
scene['Listener assumption']='Ear position X=350, Y=3353, Z=1400 mm; Z is vertical in this Blender scene.'
scene.render.resolution_x=2400;scene.render.resolution_y=1700
# Keep both complete mounts in frame, including the speaker nearest the camera.
from bpy_extras.object_utils import world_to_camera_view
bpy.context.view_layer.update()
for _ in range(50):
    projected=[world_to_camera_view(scene,wide,o.matrix_world@Vector(c)) for o in mount_objects for c in o.bound_box]
    if all(.055<p.x<.945 and .055<p.y<.945 for p in projected):break
    wide.data.lens*=.975
print('ROOM CAMERA LENS',wide.data.lens,flush=True)
bpy.ops.wm.save_as_mainfile(filepath=str(OUT/'dorm_room.blend'))

for key,cam,size in [('room',wide,(2400,1700)),('mount',close,(2000,1800)),('overview',overview,(2200,1900)),('rail-wall',railview,(2400,1700))]:
    if VIEW not in ['all',key]:continue
    hidden=[]
    if key=='room':
        for o in architecture:
            if min(v.co.y for v in o.data.vertices)>=4399:hidden.append(o)
        for o in hidden:o.hide_render=True
    if key=='overview':
        # Explicit dollhouse view: hide the roof and near-side shell only.
        hidden=[ceiling]
        for o in architecture:
            xs=[v.co.x for v in o.data.vertices];ys=[v.co.y for v in o.data.vertices];zs=[v.co.z for v in o.data.vertices]
            if max(xs)<1 or min(ys)>=4399 or min(zs)>2500:hidden.append(o)
        for o in hidden:o.hide_render=True
        cutlight=area('Cutaway softbox',(-2,3,6),(1,2,0),400,(1,.90,.79),5)
    scene.camera=cam;scene.render.resolution_x=size[0]//2 if PREVIEW else size[0];scene.render.resolution_y=size[1]//2 if PREVIEW else size[1]
    scene.render.filepath=str(OUT/(key+('-preview' if PREVIEW else '')+'.png'))
    bpy.ops.render.render(write_still=True)
    for o in hidden:o.hide_render=False
    if key=='overview':cutlight.hide_render=True
scene.camera=wide;scene.render.resolution_x=2400;scene.render.resolution_y=1700
for o in architecture:
    if min(v.co.y for v in o.data.vertices)>=4399:o.hide_render=True
scene.render.filepath=str(OUT/'room.png')
bpy.ops.wm.save_as_mainfile(filepath=str(OUT/'dorm_room.blend'))
